New logo
usethesource/rascal-website pull request #7
Opened 2022-02-22 16:38 UTC by jurgenvinju

2022-02-22 16:39 UTC, jurgenvinju commented
It seems to work. I've done my best with the CSS and HTML tricks; not my forte (to say the least)

2022-02-22 16:40 UTC, jurgenvinju commented
Test this by running `jekyll serve` and clicking the localhost http address that is printed on the console.

2022-02-22 17:13 UTC, DavyLandman commented
Took me a while to run it (docker helped in the end)

But it looks good to me.

![afbeelding](https://user-images.githubusercontent.com/179603/155183158-9f35306a-42a6-419b-8bb5-05402f39ae2a.png)
![afbeelding](https://user-images.githubusercontent.com/179603/155183193-4f775f27-bfa1-43bf-8392-b9a82567fa83.png)

2022-02-22 17:15 UTC, DavyLandman commented
Correction, on mobile it's not working:

![afbeelding](https://user-images.githubusercontent.com/179603/155183501-84242a43-2b30-476c-8805-583e0341ddec.png)

![afbeelding](https://user-images.githubusercontent.com/179603/155183583-209d8419-665b-4648-9b2c-2e19472a3577.png)

2022-02-22 17:16 UTC, DavyLandman requested changes
It's not working on mobile.

Maybe we could use the svg instead of a png?

2022-02-22 17:16 UTC, DavyLandman commented on _layouts/front.html
> +            <div class="jumbotron" style="clear: left; height:175px">
I think this specific height is messing with the mobile phone version.

2022-02-22 17:16 UTC, DavyLandman commented on assets/css/custom.css
> +      background-size: 35%;
this is most likely messing with the mobile phone version

2022-02-22 17:16 UTC, DavyLandman commented on assets/css/custom.css
> +      background-size: 100px 100px;
explicit sizes don't work well with mobilephone I'm guessing.

2022-12-20 14:46 UTC, jurgenvinju commented
history has caught up with this pr

2022-12-20 14:46 UTC, closed without merging